# proxies for detect
proxies = [
    "https://proxy.golang.org"
]
core-package = "github.com/ihatiko/go-chef-core"
core-command = "go-chef-core"
base-command = "settings"
base-package = "github.com/ihatiko/go-chef"
interval = "1h"